### ISSUE TITLE
make themes be available on source-time

### ISSUE THREAD

**Issue by alex-popov-tech** [rbong/vim-crystalline#35] opened 2020-10-22 23:05 UTC
Hey! Using your status line for a halt-year now, pretty happy with that, thanks!

One problem - i have custom theme, and i have dotfiles with install script, where nvim plugins are installed with `nvim +PlugInstall`. Since I have custom theme vim tries to source all its config files and then do command, but it fails on sourcing cause vim-crystalline is there already ( if run couple of times ) but there is not linked yet to plugged/vim-crystalline/autoload/theme/custom.vim...

Question - could you please make possible to just write function in my .vimrc with theme i need, and crystalline just pick up this function, instead of looking it in files ?

**Comment by delphinus** [comment] 2020-10-23 08:34
There is a general solution in vimscript to source scripts only when the funcs / vars exist.

```vim
" in your .vimrc
" vim-plug settings...
" When you have installed all, Vim sources crystalline here.

...

" set statusline only when the var exists
if exists('g:crystalline_theme')
" or source only when the func exists
" if exists('*crystalline#mode')
  function! StatusLine(...)
    return crystalline#mode() . ' %f%h%w%m%r '
  endfunction
  let g:crystalline_statusline_fn = 'StatusLine'
  let g:crystalline_theme = 'default'
  set laststatus=2
endif

...
```

Perhaps, more neat way to detect a plugin to be installed exists in vim-plug (I'm not familiar with vim-plug).

**Comment by alex-popov-tech** [comment] 2020-10-23 12:28
@delphinus thanks for quick answer!
The problem is - after installing plugin ( which is there in config close to `g:crystalline_theme` declaration ) there are no file with my theme in `plugged/vim-crystalline/autoload...`. So basically sourcing vim script with plugins declaration is failing 100% of time because i need to have pulled plugin to put there my theme, but for downloading plugin i need to source config, but i cannot source config because there is my custom theme declaration, etc.

Can custom theme be done with something like just `g:crystalline_theme = { ....colors goes here ... }` ? That would help

**Comment by delphinus** [comment] 2020-10-24 00:28
You want to use your own colors for crystalline? Sorry, I misunderstood that.

You do not need put your own custom color theme into `plugged/vim-crystalline/autoload...`. You only need put it any path in `&runtimepath`. I created minimal vimrc for explanation.

1. Download vim-plug.

   ```sh
   curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
   ```

2. Add vimrc

   ```sh
   vim ~/.vimrc
   ```

   ```vim
   call plug#begin('~/test/plugged')
   Plug 'rbong/vim-crystalline'
   call plug#end()

   function! StatusLine(...)
     return crystalline#mode() . crystalline#right_mode_sep('')
           \ . ' %f%h%w%m%r ' . crystalline#right_sep('', 'Fill') . '%='
           \ . crystalline#left_sep('', 'Fill') . ' %{&ft}[%{&fenc!=#""?&fenc:&enc}][%{&ff}] %l/%L %c%V %P '
   endfunction
   let g:crystalline_enable_sep = 1
   let g:crystalline_statusline_fn = 'StatusLine'

   " the name of your own theme
   let g:crystalline_theme = 'foobar'
   set laststatus=2
   ```

3. Put your own theme

   ```sh
   mkdir ~/.vim/autoload/crystalline/theme
   vim ~/.vim/autoload/crystalline/theme/foobar.vim
   ```

   ```vim
   function! crystalline#theme#foobar#set_theme() abort
     " You can write some color settings here.
     " now call default ones.
     call crystalline#theme#default#set_theme()
   endfunction
   ```

4. Run the Vim

   ```sh
   # install crystalline
   vim +PlugInstall +q
   # now you can see crystalline
   vim
   ```

**Comment by rbong** [comment] 2020-10-24 00:38
@delphinus is exactly right. I don't want to add more ways to define themes unless if it's really needed, so I'm closing this. Let me know if the issue isn't solved and will re-open.

**Closed as completed by rbong** 2020-10-24 00:38 UTC

**Comment by alex-popov-tech** [comment] 2020-10-25 01:15
oh...right, it looks like something i need, will try it out, thanks guys!
